---
memcached_user: memcache
memcached_group: memcache
memcached_memory: 64
memcached_max_object_size: 1m
memcached_port: 11_211
memcached_udp_port: 11_211
memcached_listen: 0.0.0.0
memcached_maxconn: 1024
memcached_logfile: /var/log/memcached.log
