# A simple setup for a LEMP stack using php version 5.6
#
# @author Aidan Gustard (2015)
# 
---
- hosts: all
  sudo: yes
  user: vagrant

  vars_prompt:
  - name: "version_check"
    prompt: "Which version of php 5.x to install? (3, 5 or 6)?"
    default: "6"

  roles:
     - core
     - nginx
     - mysql
     - php
     - phpmyadmin
     - memcached
