# Install php
---
- name: Enabling remi 5.5
  template: src=remi.repo dest=/etc/yum.repos.d/remi.repo

- name: Install PHP
  yum: pkg={{ item }} enablerepo=remi state=installed
  with_items:
    - php
    - php-cli
    - php-fpm
    - php-mysql
    - php-devel
    - php-pear
    - php-mbstring
    - php-mcrypt
    - php-openssl
    - php-xml
    - php-json

- name: Copying php.ini
  template: src=php.ini dest=/etc/php.ini
